### ISSUE TITLE
Upgrade Storage Library to version 7.0.0

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureBlobStorageDataBus#16]
With version 7.0.0 of the WindowsAzure.Storage library, we should package ASQ with it to allow customers to use version 7+, which they will be asking to allow them to use the latest MSFT library.

Connects to https://github.com/Particular/PlatformDevelopment/issues/731

**Comment by SimonCropp** [comment]
repo updated 

doco update blockled by https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/issues/21

**Comment by andreasohlund** [comment]
Done in the new repo, WIP pull for sample opened https://github.com/Particular/docs.particular.net/pull/1499
