### ISSUE TITLE
incorrect version due to bad merge message

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureBlobStorageDataBus#21]
This is causing gitversion to get an invalid version.
https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/commit/b62196a9894997d1647d9c35046f6c6230e1c964

need to fix the text to not contain the "release-6.2.0"

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers i will let you handle this since it will need to be coordinated with other azure devs

**Comment by andreasohlund** [comment]
No longer an issue since we moved to a new repo
