### ISSUE TITLE
Container name check

### ISSUE THREAD

**Issue by JeyDotC** [Particular/NServiceBus.AzureBlobStorageDataBus#5]
## Who's affected 

- Anyone who's using `AzureBlobStorageDataBus` and specifies invalid characters for container name

## Symptoms

- Container fails Azure validation and exception hard to understand is thrown

TODO
- [ ] Needs to be applied to NServiceBus.Azure repo for public release

**Originally reported by** @JeyDotC 
Please, check that container name is all lowercase in AzureDataBusGuard or lower case the container name before creating it, not doing so caused me to struggle for hours with a not very describing 'bad request' error.

I didn't remember that restriction on container names(my bad) but I think I shouldn't if NServiceBus is intended to reduce the amount of details I must remember to configure the DataBus feature.

If you think one just have to be careful on how to name containers, which I think is completely valid, I'd appreciate that you state that in your documentation.

Regards.

**Comment by yvesgoeleven** [comment]
Thanks for reporting, we'll add the check

**Comment by SeanFeldman** [comment]
Rules for container names: https://msdn.microsoft.com/en-us/library/azure/dd135715.aspx

**Comment by SeanFeldman** [comment]
@Particular/azure Have fixed on develop branch. Since workaround is possible (supplying proper container name), should we wait with releasing?
