### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureBlobStorageDataBus#9]
Connects to Particular/PlatformDevelopment#182

This is the AzureBlobStorageDataBus adapter epic which incorporates the work for making the AzureBlobStorageDataBus adapter async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

**Comment by SeanFeldman** [comment]
@SimonCropp the work is done on async conversion or more to be done?
